### ISSUE TITLE
AttributeError: 'module' object has no attribute 'While'

### ISSUE THREAD

**Issue by RahulBhalley** [dshieble/Music_RBM#3]
I am getting the following error:
```100%|██████████████████████████████████████████████████████████| 126/126 [00:04<00:00, 27.54it/s]
122 songs processed
Traceback (most recent call last):
  File "rbm_chords.py", line 87, in <module>
    x_sample = gibbs_sample(1) 
  File "rbm_chords.py", line 77, in gibbs_sample
    [_, _, x_sample] = control_flow_ops.While(lambda count, num_iter, *args: count < num_iter,
AttributeError: 'module' object has no attribute 'While'
```

**Comment by gofornaman** [comment]
did you solve it?

**Comment by RahulBhalley** [comment]
Since newer version of TensorFlow replaced `While` with `while_loop` replace lines 77 and 78 with

``[_, _, x_sample] = control_flow_ops.while_loop(lambda count, num_iter, *args: count < num_iter, gibbs_step, [ct, tf.constant(k), x], parallel_iterations=1, back_prop=False)``

For removing further possible errors:
- replace `tf.mul`, `tf.sub` to `tf.multiply`, `tf.subtract` respectively in lines 95, 96, and 97. 
- replace code in line 116 to `song = song[:int(np.floor(song.shape[0]/num_timesteps))*num_timesteps]` which basically uses `int` on `np.floor` to make slicing of indices integral.
